[project]
name = "nsbutils"
version = "0.1.0"
description = "Neuroimaging tools developed by the Neural Systems and Behaviour Lab"
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
    "lapy>=1.6.0",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
    "surfplot>=0.2.0",
]

[project.optional-dependencies]
testing = [
    "pytest>=8.4.2",
]
plotting = [
    "imageio>=2.37.2",
    "imageio-ffmpeg>=0.6.0",
    "ipywidgets>=8.1.8",
    "nest-asyncio2>=1.7.2",
    "pyvista>=0.46.5",
    "trame>=3.12.0",
    "trame-vtk>=2.11.6",
    "trame-vuetify>=3.2.1",
]
tutorials = [
    "ipykernel>=6.31.0",
    "neuromodes @ git+https://github.com/NSBLab/neuromodes.git@dev",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nsbutils"]

[tool.pytest.ini_options]
python_functions = ["test_"]
python_files = ["test_*.py",]
testpaths = ["tests",]

[project.urls]
"Homepage" = "https://nsbutils.readthedocs.io"
